// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Data;
@class Data_Builder;
@class Person;
@class Person_Builder;

@interface PersonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Person : PBGeneratedMessage {
@private
  BOOL hasEntryId_:1;
  BOOL hasFirstName_:1;
  BOOL hasLastName_:1;
  BOOL hasPhone_:1;
  BOOL hasEmail_:1;
  BOOL hasAddress_:1;
  BOOL hasCity_:1;
  BOOL hasZip_:1;
  BOOL hasState_:1;
  BOOL hasCountry_:1;
  BOOL hasDescription_:1;
  BOOL hasPassword_:1;
  BOOL hasCreatedOn_:1;
  BOOL hasModifiedOn_:1;
  int32_t entryId;
  NSString* firstName;
  NSString* lastName;
  NSString* phone;
  NSString* email;
  NSString* address;
  NSString* city;
  NSString* zip;
  NSString* state;
  NSString* country;
  NSString* description;
  NSString* password;
  NSString* createdOn;
  NSString* modifiedOn;
}
- (BOOL) hasEntryId;
- (BOOL) hasFirstName;
- (BOOL) hasLastName;
- (BOOL) hasPhone;
- (BOOL) hasEmail;
- (BOOL) hasAddress;
- (BOOL) hasCity;
- (BOOL) hasZip;
- (BOOL) hasState;
- (BOOL) hasCountry;
- (BOOL) hasDescription;
- (BOOL) hasPassword;
- (BOOL) hasCreatedOn;
- (BOOL) hasModifiedOn;
@property (readonly) int32_t entryId;
@property (readonly, retain) NSString* firstName;
@property (readonly, retain) NSString* lastName;
@property (readonly, retain) NSString* phone;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* address;
@property (readonly, retain) NSString* city;
@property (readonly, retain) NSString* zip;
@property (readonly, retain) NSString* state;
@property (readonly, retain) NSString* country;
@property (readonly, retain) NSString* description;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* createdOn;
@property (readonly, retain) NSString* modifiedOn;

+ (Person*) defaultInstance;
- (Person*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Person_Builder*) builder;
+ (Person_Builder*) builder;
+ (Person_Builder*) builderWithPrototype:(Person*) prototype;

+ (Person*) parseFromData:(NSData*) data;
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromInputStream:(NSInputStream*) input;
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Person_Builder : PBGeneratedMessage_Builder {
@private
  Person* result;
}

- (Person*) defaultInstance;

- (Person_Builder*) clear;
- (Person_Builder*) clone;

- (Person*) build;
- (Person*) buildPartial;

- (Person_Builder*) mergeFrom:(Person*) other;
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEntryId;
- (int32_t) entryId;
- (Person_Builder*) setEntryId:(int32_t) value;
- (Person_Builder*) clearEntryId;

- (BOOL) hasFirstName;
- (NSString*) firstName;
- (Person_Builder*) setFirstName:(NSString*) value;
- (Person_Builder*) clearFirstName;

- (BOOL) hasLastName;
- (NSString*) lastName;
- (Person_Builder*) setLastName:(NSString*) value;
- (Person_Builder*) clearLastName;

- (BOOL) hasPhone;
- (NSString*) phone;
- (Person_Builder*) setPhone:(NSString*) value;
- (Person_Builder*) clearPhone;

- (BOOL) hasEmail;
- (NSString*) email;
- (Person_Builder*) setEmail:(NSString*) value;
- (Person_Builder*) clearEmail;

- (BOOL) hasAddress;
- (NSString*) address;
- (Person_Builder*) setAddress:(NSString*) value;
- (Person_Builder*) clearAddress;

- (BOOL) hasCity;
- (NSString*) city;
- (Person_Builder*) setCity:(NSString*) value;
- (Person_Builder*) clearCity;

- (BOOL) hasZip;
- (NSString*) zip;
- (Person_Builder*) setZip:(NSString*) value;
- (Person_Builder*) clearZip;

- (BOOL) hasState;
- (NSString*) state;
- (Person_Builder*) setState:(NSString*) value;
- (Person_Builder*) clearState;

- (BOOL) hasCountry;
- (NSString*) country;
- (Person_Builder*) setCountry:(NSString*) value;
- (Person_Builder*) clearCountry;

- (BOOL) hasDescription;
- (NSString*) description;
- (Person_Builder*) setDescription:(NSString*) value;
- (Person_Builder*) clearDescription;

- (BOOL) hasPassword;
- (NSString*) password;
- (Person_Builder*) setPassword:(NSString*) value;
- (Person_Builder*) clearPassword;

- (BOOL) hasCreatedOn;
- (NSString*) createdOn;
- (Person_Builder*) setCreatedOn:(NSString*) value;
- (Person_Builder*) clearCreatedOn;

- (BOOL) hasModifiedOn;
- (NSString*) modifiedOn;
- (Person_Builder*) setModifiedOn:(NSString*) value;
- (Person_Builder*) clearModifiedOn;
@end

@interface Data : PBGeneratedMessage {
@private
  NSMutableArray* mutablePersonList;
}
- (NSArray*) personList;
- (Person*) personAtIndex:(int32_t) index;

+ (Data*) defaultInstance;
- (Data*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Data_Builder*) builder;
+ (Data_Builder*) builder;
+ (Data_Builder*) builderWithPrototype:(Data*) prototype;

+ (Data*) parseFromData:(NSData*) data;
+ (Data*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Data*) parseFromInputStream:(NSInputStream*) input;
+ (Data*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Data*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Data*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Data_Builder : PBGeneratedMessage_Builder {
@private
  Data* result;
}

- (Data*) defaultInstance;

- (Data_Builder*) clear;
- (Data_Builder*) clone;

- (Data*) build;
- (Data*) buildPartial;

- (Data_Builder*) mergeFrom:(Data*) other;
- (Data_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Data_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) personList;
- (Person*) personAtIndex:(int32_t) index;
- (Data_Builder*) replacePersonAtIndex:(int32_t) index with:(Person*) value;
- (Data_Builder*) addPerson:(Person*) value;
- (Data_Builder*) addAllPerson:(NSArray*) values;
- (Data_Builder*) clearPersonList;
@end

